### ISSUE TITLE
Sourcemaps linked correctly? 

### ISSUE THREAD

**Issue by jeffpatzer** [scttcper/tinycolor#199]
I'm noticing this warning in my local dev terminal since upgrading the package recently. 

```
WARNING in ./node_modules/@ctrl/tinycolor/dist/module/util.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/src/main/webpack/node_modules/@ctrl/tinycolor/src/util.ts' file: Error: ENOENT: no such file or directory, open '/src/main/webpack/node_modules/@ctrl/tinycolor/src/util.ts'
Error: Failed to parse source map from '/src/main/webpack/node_modules/@ctrl/tinycolor/src/util.ts' file: Error: ENOENT: no such file or directory, open '/src/main/webpack/node_modules/@ctrl/tinycolor/src/util.ts'
    at fetchFromFilesystem (/src/main/webpack/node_modules/source-map-loader/dist/utils.js:130:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ ./node_modules/@ctrl/tinycolor/dist/module/index.js 4:0-54 101:17-27 198:51-58 210:51-58 296:16-23 320:16-23 350:16-23 361:16-23
 @ ./node_modules/@ctrl/tinycolor/dist/module/public_api.js
 @ ./funnel/components/header/header-full-width.tsx
 @ ./funnel/pages/Funnel.tsx
 @ ./funnel/pages/funnel-loader.tsx
```

util.js is showing a reference to `../src/util.ts`
```
{"version":3,"file":"util.js","sourceRoot":"","sources":["../src/util.ts"],"names":[],"mappings":";;;AAAA;;;GAGG;AACH,SAAgB,OAAO,CAAC,CAAM,EAAE,GAAW;IACzC,IAAI,cAAc,CAAC,CAAC,CAAC,EAAE;QACrB,CAAC,GAAG,MAAM,CAAC;KACZ;IAED,MAAM,SAAS,GAAG,YAAY,CAAC,CAAC,CAAC,CAAC;IAClC,CAAC,GAAG,GAAG,KAAK,GAAG,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,IAAI,CAAC,GAAG,CAAC,GAAG,EAAE,IAAI,CAAC,GAAG,CAAC,CAAC,EAAE,UAAU,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC;IAEhE,+CAA+C;IAC/C,IAAI,SAAS,EAAE;QACb,CAAC,GAAG,QAAQ,CAAC,MAAM,CAAC,CAAC,GAAG,GAAG,CAAC,EAAE,EAAE,CAAC,GAAG,GAAG,CAAC;KACzC;IAED,wCAAwC;IACxC,IAAI,IAAI,CAAC,GAAG,CAAC,CAAC,GAAG,GAAG,CAAC,GAAG,QAAQ,EAAE;QAChC,OAAO,CAAC,CAAC;KACV;IAED,gDAAgD;IAChD,IAAI,GAAG,KAAK,GAAG,EAAE;QACf,kCAAkC;QAClC,sDAAsD;QACtD,4BAA4B;QAC5B,CAAC,GAAG,CAAC,CAAC,GAAG,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,GAAG,GAAG,CAAC,GAAG,GAAG,CAAC,CAAC,CAAC,CAAC,GAAG,GAAG,CAAC,GAAG,UAAU,CAAC,MAAM,CAAC,GAAG,CAAC,CAAC,CAAC;KACnE;SAAM;QACL,kCAAkC;QAClC,iDAAiD;QACjD,CAAC,GAAG,CAAC,CAAC,GAAG,GAAG,CAAC,GAAG,UAAU,CAAC,MAAM,CAAC,GAAG,CAAC,CAAC,CAAC;KACzC;IAED,OAAO,CAAC,CAAC;AACX,CAAC;AA/BD,0BA+BC;AAED;;;GAGG;AACH,SAAgB,OAAO,CAAC,GAAW;IACjC,OAAO,IAAI,CAAC,GAAG,CAAC,CAAC,EAAE,IAAI,CAAC,GAAG,CAAC,CAAC,EAAE,GAAG,CAAC,CAAC,CAAC;AACvC,CAAC;AAFD,0BAEC;AAED;;;;GAIG;AACH,SAAgB,cAAc,CAAC,CAAkB;IAC/C,OAAO,OAAO,CAAC,KAAK,QAAQ,IAAI,CAAC,CAAC,QAAQ,CAAC,GAAG,CAAC,IAAI,UAAU,CAAC,CAAC,CAAC,KAAK,CAAC,CAAC;AACzE,CAAC;AAFD,wCAEC;AAED;;;GAGG;AACH,SAAgB,YAAY,CAAC,CAAkB;IAC7C,OAAO,OAAO,CAAC,KAAK,QAAQ,IAAI,CAAC,CAAC,QAAQ,CAAC,GAAG,CAAC,CAAC;AAClD,CAAC;AAFD,oCAEC;AAED;;;GAGG;AACH,SAAgB,UAAU,CAAC,CAAmB;IAC5C,CAAC,GAAG,UAAU,CAAC,CAAW,CAAC,CAAC;IAE5B,IAAI,KAAK,CAAC,CAAC,CAAC,IAAI,CAAC,GAAG,CAAC,IAAI,CAAC,GAAG,CAAC,EAAE;QAC9B,CAAC,GAAG,CAAC,CAAC;KACP;IAED,OAAO,CAAC,CAAC;AACX,CAAC;AARD,gCAQC;AAED;;;GAGG;AACH,SAAgB,mBAAmB,CAAC,CAAkB;IACpD,IAAI,CAAC,IAAI,CAAC,EAAE;QACV,OAAO,GAAG,MAAM,CAAC,CAAC,CAAC,GAAG,GAAG,GAAG,CAAC;KAC9B;IAED,OAAO,CAAC,CAAC;AACX,CAAC;AAND,kDAMC;AAED;;;GAGG;AACH,SAAgB,IAAI,CAAC,CAAS;IAC5B,OAAO,CAAC,CAAC,MAAM,KAAK,CAAC,CAAC,CAAC,CAAC,GAAG,GAAG,CAAC,CAAC,CAAC,CAAC,MAAM,CAAC,CAAC,CAAC,CAAC;AAC9C,CAAC;AAFD,oBAEC"}
```

Are the mapping files meant to be part of the distribution? If so, looks like they aren't referencing the distributed .js files.

**Comment by jeffpatzer** [comment]
Thanks 🙏!
